config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pokemons
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
    SPECIES = %w(dog cat bird horse)
    validates :name, presence: true
    validates :species, inclusion: { in: SPECIES } 
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
    validates :name, :species, :address, presence: true
    validates :species, inclusion: { in: %w(grass water fire bug normal electric) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def index
    end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
    before_action :set_pet, only: [:show, :edit, :update, :destroy]
    def index
      @pets = Pet.all
    end
  
    def show
    end
  
    def new
      @pet = Pet.new
    end
  
    def create
      @pet = Pet.new(pet_params)
      if @pet.save
        redirect_to pet_path(@pet)
      else
        render 'new'   #re-render to the new page if failed
      end
    end
  
    def edit
    end
  
    def update
      if @pet.update(pet_params)
        redirect_to pet_path(@pet)
      else
        render 'edit' #re-render to the edit- page if failed
      end
    end
  
    def destroy
      @pet.destroy
      redirect_to pets_path
    end
  
    private

    def set_pet
      @pet = Pet.find(params[:id])
    end
  
    def pet_params
      params.require(:pet).permit(:name, :address, :species, :found_on)
    end
  
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
    before_action :set_pokemon, only: [:show, :edit, :update, :destroy]

    def index
        @pokemons = Pokemon.all
    end

    def show; end

    def new
        @pokemon = Pokemon.new
    end    

    def create
        @pokemon = Pokemon.new(pokemon_params)
        @pokemon.save
        redirect_to pokemon_path(@pokemon)
    end

    def edit; end

    def update
        @pokemon.update(pokemon_params)
        redirect_to pokemon_path(@pokemon)   
    end

    def destroy
        @pokemon.destroy
        redirect_to pokemons_path
    end
    private

    def set_pokemon
        @pokemon = Pokemon.find(params[:id])
    end

    def pokemon_params
        params.require(:pokemon).permit(:name, :species, :address, :found_on)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">  
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<%= bootstrap_form_for(@pet, class: 'form') do |f| %>
  <%= f.text_field :name %>
  <%= f.text_area :address %>
  <%= f.select :species, collection: Pet::SPECIES %>
  <%= f.date_select :found_on %>
  <%= f.submit %>
<% end %>

app/views/pets/edit.html.erb
<h1>Edit a new pet</h1>

<%= render "form" %>

app/views/pets/index.html.erb
<h1>All pets</h1>

<ul>
  <% @pets.each do |pet| %>
    <li><%= link_to pet.name, pet_path(pet) %></li>
  <% end %>
</ul>

<%= link_to "Add a pet", pets_new_path %>

app/views/pets/new.html.erb
<h1>Add a new pet</h1>

<%= render "form" %>

app/views/pets/show.html.erb
<h1><%= @pet.name %> <small>(<%= @pet.species %>)</small></h1>
<ul>
  <li>Address: <%= @pet.address %></li>
  <li>Found on: <%= @pet.found_on %></li>
</ul>

<%= link_to "Edit #{@pet.name}", edit_pet_path(@pet) %>
<br>
<%= link_to "Delete #{@pet.name}", pet_path(@pet), method: :delete, data: { confirm: "This pet got home?"} %>
<br>
<%= link_to "Back to all pets", pets_path %>

app/views/pokemons/edit.html.erb
<%= form_for(@pokemon) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :species %>
  <%= f.text_field :species %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :found_on %>
  <%= f.text_field :found_on %>
  <%= f.submit %>
<% end %>

app/views/pokemons/index.html.erb
<h1>Hello Pokemon</h1>
<% @pokemons.each do |pokemon| %>
    <h2><%= link_to pokemon.name, pokemon_path(pokemon) %></h2>
<% end %>

<%= link_to 'create a pokemon', new_pokemon_path %>

app/views/pokemons/new.html.erb
<%= form_for(@pokemon) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :species %>
  <%= f.text_field :species %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :found_on %>
  <%= f.text_field :found_on %>
  <%= f.submit %>
<% end %>

app/views/pokemons/show.html.erb
<h1>Pokemon Info</h1>

<h3><%= @pokemon.name %></h3>
<p><%= @pokemon.species %></p>
<p><%= @pokemon.address %></p>
<p><%= @pokemon.found_on %></p>

<%= link_to "home", pokemons_path %>
<%= link_to "edit", edit_pokemon_path %>
<%= link_to "delete", pokemon_path(@pokemon), method: :delete %>